/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.GUI;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;
import javax.swing.JOptionPane;
import org.example.JSONToJavaClassConverter;

/**
 *
 * @author Johan
 */
public class Converter extends javax.swing.JFrame {

    /**
     * Creates new form Converter
     */
    
    private String filePath;
    
    public Converter() {
        initComponents();
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
        this.displayJSONContent();
        this.convertJSONToJava();
    }
    
    private void displayJSONContent() {
        try {
            // Lee el contenido del archivo JSON
            String jsonContent = new String(Files.readAllBytes(Paths.get(this.filePath)));

            // Muestra el contenido en el área de texto correspondiente
            this.textAreaJSON.setText(jsonContent);
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
    }
    
    private void convertJSONToJava() {
        JSONToJavaClassConverter jsonToJava = new JSONToJavaClassConverter(this.filePath);
        
        // Clase para ir concatenando los strings de las clases y atributos
        StringBuilder javaFileConverted = new StringBuilder();
        
        if (jsonToJava.isAValidJSON()) {
            jsonToJava.getFinalClasses().forEach((className, attributes) -> {
                javaFileConverted.append("class ").append(className).append(" {\n");
                attributes.forEach(attribute -> {
                    javaFileConverted.append("        ").append(attribute).append("\n");
                });
                javaFileConverted.append("}").append("\n\n");
            });
        } else {
            JOptionPane.showMessageDialog(this, "El archivo JSON no es válido",
                    "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        
        // Muestra el contenido del archivo Java convertido en el área de texto correspondiente
        this.textAreaConvertedJavaClass.setText(javaFileConverted.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaJSON = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaConvertedJavaClass = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaJSON.setEditable(false);
        textAreaJSON.setBackground(new java.awt.Color(255, 255, 255));
        textAreaJSON.setColumns(20);
        textAreaJSON.setFont(new java.awt.Font("Roboto Slab Light", 0, 18)); // NOI18N
        textAreaJSON.setRows(5);
        jScrollPane1.setViewportView(textAreaJSON);

        textAreaConvertedJavaClass.setEditable(false);
        textAreaConvertedJavaClass.setBackground(new java.awt.Color(255, 255, 255));
        textAreaConvertedJavaClass.setColumns(20);
        textAreaConvertedJavaClass.setFont(new java.awt.Font("Roboto Slab Light", 0, 18)); // NOI18N
        textAreaConvertedJavaClass.setRows(5);
        jScrollPane2.setViewportView(textAreaConvertedJavaClass);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Converter();
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaConvertedJavaClass;
    private javax.swing.JTextArea textAreaJSON;
    // End of variables declaration//GEN-END:variables
}
